/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Sierra.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from "valtio"
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';

export function Sierra(props) {
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)
  const { nodes, materials } = useGLTF('/models/Sierra.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.antennas_.geometry} material={materials.wire_008110135} />
      <mesh geometry={nodes.bottom.geometry} material={materials.trim} />
      <mesh geometry={nodes.Body.geometry} material={materials.BaseMtl}  material-color={snap1.base.BaseMtl} visible={overlay === 1}/>
      <mesh geometry={nodes.front_arches.geometry} material={materials.tires} />
      <mesh geometry={nodes.front_bumper.geometry} material={materials.tires} />
      <mesh geometry={nodes.glass.geometry} material={materials.glass} />
      <mesh geometry={nodes.headlights.geometry} material={materials.wire_008110135} />
      <mesh geometry={nodes.headlights_text.geometry} material={materials.wire_115115115} />
      <mesh geometry={nodes.interior.geometry} material={materials.wire_204204204} />
      <mesh geometry={nodes.left_front_rim.geometry} material={materials.wire_177028149} />
      <mesh geometry={nodes.left_front_tire.geometry} material={materials.tires} />
      <mesh geometry={nodes.left_rear_rim.geometry} material={materials.wire_177028149} />
      <mesh geometry={nodes.left_rear_tire.geometry} material={materials.tires} />
      <mesh geometry={nodes.logo.geometry} material={materials.wire_115115115} />
      <mesh geometry={nodes.radiator.geometry} material={materials.wire_008110135} />
      <mesh geometry={nodes.radiator_grille.geometry} material={materials.wire_008110135} />
      <mesh geometry={nodes.rear_arches.geometry} material={materials.tires} />
      <mesh geometry={nodes.rear_bumper.geometry} material={materials.tires} />
      <mesh geometry={nodes.rear_lights.geometry} material={materials['glass.001']} />
      <mesh geometry={nodes.right_front_rim.geometry} material={materials.wire_177028149} />
      <mesh geometry={nodes.right_front_tire.geometry} material={materials.tires} />
      <mesh geometry={nodes.right_rear_rim.geometry} material={materials.wire_177028149} />
      <mesh geometry={nodes.right_rear_tire.geometry} material={materials.tires} />
      <mesh geometry={nodes.side_mirrors.geometry} material={materials.wire_088199225} />
      <mesh geometry={nodes.spare_rim.geometry} material={materials.trim} />
      <mesh geometry={nodes.spare_tire.geometry} material={materials.tires} />
      <mesh geometry={nodes.trunk.geometry} material={materials.trim} />
      <mesh geometry={nodes.wipers.geometry} material={materials.wire_184155229} />
      <mesh geometry={nodes.element_of_front_bumper001.geometry} material={materials.trim} />
      <mesh geometry={nodes.element_of_front_bumper002.geometry} material={materials.trim} />
      <mesh geometry={nodes.element_of_front_bumper003.geometry} material={materials.trim} />
      <mesh geometry={nodes.element_of_front_bumper004.geometry} material={materials.trim} />
      <mesh geometry={nodes.Body001.geometry} material={materials.Slaughter}  material-color={snap1.base.BaseMtl} visible={overlay === 2}/>
      <mesh geometry={nodes.Body002.geometry} material={materials.BatLady}  material-color={snap1.base.BaseMtl} visible={overlay === 3}/>
      <mesh geometry={nodes.Body003.geometry} material={materials.BrakeLine}  material-color={snap1.base.BaseMtl} visible={overlay === 4}/>
      <mesh geometry={nodes.Body004.geometry} material={materials.Danger}  material-color={snap1.base.BaseMtl} visible={overlay === 5}/>
      <mesh geometry={nodes.Body005.geometry} material={materials.Embers}  material-color={snap1.base.BaseMtl} visible={overlay === 6}/>
      <mesh geometry={nodes.Body006.geometry} material={materials.SpiderID}  material-color={snap1.base.BaseMtl} visible={overlay === 7}/>
      <mesh geometry={nodes.Body007.geometry} material={materials.Fluid}  material-color={snap1.base.BaseMtl} visible={overlay === 8}/>
      <mesh geometry={nodes.Body008.geometry} material={materials.HotRods}  material-color={snap1.base.BaseMtl} visible={overlay === 9}/>
      <mesh geometry={nodes.Body009.geometry} material={materials.Mayan}  material-color={snap1.base.BaseMtl} visible={overlay === 10}/>
      <mesh geometry={nodes.Body010.geometry} material={materials.SeaBreeze}  material-color={snap1.base.BaseMtl} visible={overlay === 11}/>
      <mesh geometry={nodes.Body011.geometry} material={materials.ShapeShifter}  material-color={snap1.base.BaseMtl} visible={overlay === 12}/>
      <mesh geometry={nodes.Body012.geometry} material={materials.Silk}  material-color={snap1.base.BaseMtl} visible={overlay === 13}/>
      <mesh geometry={nodes.Body013.geometry} material={materials.SnakeSkin}  material-color={snap1.base.BaseMtl} visible={overlay === 14}/>
      <mesh geometry={nodes.Body014.geometry} material={materials.Flare}  material-color={snap1.base.BaseMtl} visible={overlay === 15}/>
      <mesh geometry={nodes.Body015.geometry} material={materials.Dominator}  material-color={snap1.base.BaseMtl} visible={overlay === 16}/>
      <mesh geometry={nodes.Body016.geometry} material={materials.TopGun}  material-color={snap1.base.BaseMtl} visible={overlay === 17}/>
      <mesh geometry={nodes.Body017.geometry} material={materials.Explosion}  material-color={snap1.base.BaseMtl} visible={overlay === 18}/>
      <mesh geometry={nodes.Body018.geometry} material={materials.WildWest}  material-color={snap1.base.BaseMtl} visible={overlay === 19}/>
      <mesh geometry={nodes.Body019.geometry} material={materials.Zombie}  material-color={snap1.base.BaseMtl} visible={overlay === 20}/>
    </group>
  )
}

useGLTF.preload('/models/Sierra.glb')
